apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: restaurant
data:
  APP_TITLE: "Restaurant Application"
  MONGO_URI: "mongodb://mongo:27017/restaurantdb"
  MONGO_DB_NAME: "restaurantdb"
  MONGO_AUTH_SOURCE: "admin"