apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: restaurant
  labels:
    app.kubernetes.io/name: restaurant-app
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  django-secret-key: "REPLACE_WITH_LONG_RANDOM_STRING"
  mongo-root-username: "admin"
  mongo-root-password: "REPLACE_WITH_MONGO_PASSWORD"
