apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: restaurant
  labels:
    app.kubernetes.io/name: restaurant-app
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  django-secret-key: DJANGO_SECRET_KEY
  mongo-root-username: MONGO_ROOT_USERNAME
  mongo-root-password: MONGO_ROOT_PASSWORD
